language: 
  - objective-c

osx_image: 
  - xcode9.4

script:
  - xcodebuild -workspace 'essentia-bridges-api-ios.xcworkspace' -scheme 'essentia-bridges-api-ios' -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.4'